### PR TITLE
DEV: Switch from Travis to Actions

### PR DESCRIPTION
**Pull request by OsamaSayegh**
Travis CI has a feature where you can allow failures from certain jobs in the build matrix. We use that feature here to test rails_multisite against Rails master and failures in tests against Rails master don't cause commits/PRs to display an ❌

Github Actions don't have this feature (see https://github.com/actions/toolkit/issues/399), that means commits/PRs will always display an ❌ and we have to manually ensure failures are not coming from our Rails master tests when committing or merging PRs.

Thoughts here @SamSaffron? Can we live with that? If not, we can keep Travis on this repo until Github Actions implement this feature or we can remove Rails master from our build matrix.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Travis CI is mature, GitHub Actions have the hype.

**Comment by szepeviktor** [comment]
Wouldn't it be beneficial to set up the name in a way that it will make it to the screen:

kép

**Comment by szepeviktor** [comment]
You can say `continue-on-error: ${{ matrix.experimental == 'OK to fail' }}` so you don't need another variable.

**Comment by OsamaSayegh** [comment]
Done, thank you @szepeviktor

**Comment by szepeviktor** [comment]
💥 `"` ➡️ `'`

**Comment by OsamaSayegh** [comment]
If you don't mind @szepeviktor, I'm going to delete all the replies here and squish all commits to clean this up. Thank you for your time 💖

**Comment by szepeviktor** [comment]
All right.

kép 😻

**Comment by szepeviktor** [comment]
We may have caught a 🐛 

```
Failures:

  1) RailsMultisite::ConnectionManagement two dbs can exectue a queries concurrently per db
     Failure/Error: expect(threads.length).to eq(2)

       expected: 2
            got: 1

       (compared using ==)
     # ./spec/connection_management_spec.rb:88:in `block (3 levels) in <top (required)>'
```

**Comment by OsamaSayegh** [comment]
I ran the tests locally with the same seed but I could never repro. I think this particular test case is flakey and probably there is no real bug.

**Pull request merged**
